services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./docker-data/mp:/data
    ports:
      - 8030:8025
      - 1030:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
