name: E2E Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies in e2e directory
        run: |
          cd e2e
          pnpm install

      - name: Run pnpm exec playwright install
        run: |
          cd e2e
          pnpm exec playwright install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run E2E tests
        run: |
          chmod +x ./docker-e2e.sh
          ./docker-e2e.sh
